### ISSUE TITLE
Compute publication metadata

### ISSUE THREAD

**Issue by jdp1ps** [CRISalid-esr/crisalid-ikg#156]
The “bibliographic source policies” configuration file defines the rules used to merge bibliographic source references (Hal, OpenAlex, etc.). 

```
harvesters:
  # The list of enabled harvesters at institution level.
  # The order of harvesters matters: it will be used to determine the document type and hence
  # the policy to apply in case of unclear document types (conflicts between sources).
  - hal
  - idref
  - scanr
  - scopus
  - openalex
policies:
  # Example policy 1: strategy for articles, documents of unknown type, and default documents.
  # "global_richest" prioritizes sources based on the richness of metadata for a source record taken as a whole.
  - types:
      - default     # Used as a fallback for documents with no specific type.
      - unknown     # Used for documents whose type is unknown.
      - article     # Applied to articles.
    type: "global_richest"
    parameters:
      # Scoring weights for metadata fields.
      title: 10       # Each character in the title is worth 10 points.
      abstract: 1     # Each character in the abstract is worth 1 point.
      authors: 40     # Each author is worth 40 points.
      keywords: 30    # Each keyword is worth 30 points.
  # Example policy 2: Strategy for books and theses.
  # "source_order" retrieves information in the order of specified harvesters.
  # Harvesters not listed here will be ignored for this type of document.
  - types:
      - book          # Applied to books.
      - thesis        # Applied to theses.
    type: "source_order"
    harvesters:
      - idref
      - hal
      - openalex
# Another available strategy could be "richest_by_field" 
# which priorities the metadata field by field based on their richness.
```
